### ISSUE TITLE
Welcome message doesn't disappear

### ISSUE THREAD

**Issue by aedm** [freegyes/TIL#4]
"This is a sample reference and will always show up if this list would be empty." -- it also shows up if the list isn't empty.

**Comment by freegyes** [comment]
Couldn't reproduce that. (If I delete the welcome message with another message present it does not come back.)

Please describe the steps how you've achieved this behaviour.

**Comment by freegyes** [comment]
or you mean it doesn't disappear _automatically_?

**Comment by aedm** [comment]
Yes, I though it's supposed to disappear automatically.
